export const MOD_STUDIO_STYLES = `
.ck-mod-studio{--ck-bg:#111827;--ck-panel:#182235;--ck-line:#334155;--ck-text:#e5e7eb;--ck-muted:#94a3b8;--ck-accent:#38bdf8;display:grid;grid-template-rows:auto auto minmax(360px,1fr) minmax(150px,.36fr);min-height:680px;background:var(--ck-bg);color:var(--ck-text);font:13px/1.4 ui-sans-serif,system-ui,sans-serif;border:1px solid var(--ck-line)}
.ck-mod-studio *{box-sizing:border-box}.ck-mod-studio button,.ck-mod-studio input,.ck-mod-studio select,.ck-mod-studio textarea{font:inherit}.ck-mod-studio button,.ck-mod-studio select,.ck-mod-studio input{background:#0f172a;color:var(--ck-text);border:1px solid var(--ck-line);border-radius:4px;padding:5px 8px}.ck-mod-studio button{cursor:pointer}.ck-mod-studio button:hover{border-color:var(--ck-accent)}.ck-mod-studio button:disabled{opacity:.5;cursor:not-allowed}
.ck-mod-studio-toolbar,.ck-mod-studio-actions,.ck-mod-studio-tabs,.ck-mod-studio-panel-tabs{display:flex;align-items:center;gap:6px;padding:7px;border-bottom:1px solid var(--ck-line)}.ck-mod-studio-toolbar{justify-content:space-between;flex-wrap:wrap}.ck-mod-studio-project-tools,.ck-mod-studio-runtime-tools{display:flex;align-items:center;gap:6px;flex-wrap:wrap}
.ck-mod-studio-save[data-state=SAVED]{color:#86efac}.ck-mod-studio-save[data-state=SAVING]{color:#fde68a}.ck-mod-studio-save[data-state=CONFLICT]{color:#fca5a5}.ck-mod-studio-save[data-state=OFFLINE]{color:#fdba74}
.ck-mod-studio-main{display:grid;grid-template-columns:230px minmax(0,1fr) 260px;min-height:0}.ck-mod-studio-explorer,.ck-mod-studio-settings{background:var(--ck-panel);overflow:auto;padding:8px}.ck-mod-studio-explorer{border-right:1px solid var(--ck-line)}.ck-mod-studio-settings{border-left:1px solid var(--ck-line)}.ck-mod-studio-editor-column{display:grid;grid-template-rows:auto minmax(0,1fr);min-width:0}
.ck-mod-studio-editor{min-height:0;position:relative}.ck-mod-studio-textarea{width:100%;height:100%;min-height:330px;resize:none;background:#0b1020;color:var(--ck-text);border:0;padding:12px;font:13px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}.ck-mod-studio-editor-notice{padding:4px 8px;background:#78350f;color:#ffedd5}
.ck-mod-studio-section{margin-bottom:12px}.ck-mod-studio-section-header{display:flex;align-items:center;justify-content:space-between;color:var(--ck-muted);font-weight:700;text-transform:uppercase;font-size:11px;margin-bottom:4px}.ck-mod-studio-file{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:3px;align-items:center}.ck-mod-studio-file>button:first-child{text-align:left;overflow:hidden;text-overflow:ellipsis;border:0;background:transparent}.ck-mod-studio-file>button:not(:first-child){padding:1px 4px}
.ck-mod-studio-tabs{padding:4px;overflow:auto}.ck-mod-studio-tab[data-active=true],.ck-mod-studio-panel-tab[data-active=true]{border-color:var(--ck-accent);color:#bae6fd}.ck-mod-studio-tab{white-space:nowrap}.ck-mod-studio-tab span{margin-left:7px;color:var(--ck-muted)}
.ck-mod-studio-settings label{display:grid;gap:3px;margin-bottom:9px;color:var(--ck-muted)}.ck-mod-studio-settings input,.ck-mod-studio-settings select{width:100%}.ck-mod-studio-new{display:none;gap:6px;align-items:center;width:100%;padding:7px;border-bottom:1px solid var(--ck-line)}.ck-mod-studio-new[data-open=true]{display:flex}.ck-mod-studio-new input{flex:1}
.ck-mod-studio-bottom{display:grid;grid-template-rows:auto minmax(0,1fr);min-height:0;border-top:1px solid var(--ck-line)}.ck-mod-studio-panel{display:none;overflow:auto;padding:8px}.ck-mod-studio-panel[data-active=true]{display:block}.ck-mod-studio-panel pre{white-space:pre-wrap;margin:0;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}.ck-mod-studio-problem{display:grid;grid-template-columns:auto auto 1fr;gap:8px;padding:3px;border-bottom:1px solid #243247}.ck-mod-studio-problem[data-source=rustc]{color:#fecaca}.ck-mod-studio-problem[data-source=local-advisory]{color:#fde68a}
.ck-mod-studio-status{color:var(--ck-muted)}.ck-mod-studio-invoke{display:grid;grid-template-columns:180px 1fr auto;gap:6px}.ck-mod-studio-invoke textarea{min-height:70px;background:#0f172a;color:var(--ck-text);border:1px solid var(--ck-line)}.ck-mod-studio-empty{color:var(--ck-muted);padding:8px}
@media(max-width:900px){.ck-mod-studio-main{grid-template-columns:180px minmax(0,1fr)}.ck-mod-studio-settings{display:none}}@media(max-width:620px){.ck-mod-studio-main{grid-template-columns:1fr}.ck-mod-studio-explorer{display:none}}
`;
